# Generated by Django 6.0.4 on 2026-05-11 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('single_room', 'Single Room'), ('self_contained', 'Self-Contained Room'), ('studio', 'Studio Apartment'), ('1_bed', '1 Bedroom Apartment'), ('2_bed', '2 Bedroom Apartment'), ('3_plus_bed', '3+ Bedroom Apartment'), ('bungalow', 'Bungalow'), ('standalone', 'Standalone House'), ('apartment_block', 'Apartment Block'), ('condo_block', 'Condominium Block'), ('flat', 'Flat (Multi-Floor Building)')], max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('under_maintenance', 'Under Maintenance'), ('pending_verification', 'Pending Verification')], default='pending_verification', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('location', models.CharField(max_length=255)),
                ('is_multi_unit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.property')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
