# Generated by Django 6.0.4 on 2026-05-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='building_plans',
            field=models.FileField(blank=True, null=True, upload_to='properties/documents/'),
        ),
        migrations.AddField(
            model_name='property',
            name='hero_image',
            field=models.FileField(blank=True, null=True, upload_to='properties/hero/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_1',
            field=models.FileField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
        migrations.AddField(
            model_name='property',
            name='lc1_letter',
            field=models.FileField(blank=True, null=True, upload_to='properties/documents/'),
        ),
        migrations.AddField(
            model_name='property',
            name='occupancy_permit',
            field=models.FileField(blank=True, null=True, upload_to='properties/documents/'),
        ),
        migrations.AddField(
            model_name='property',
            name='security_agreement',
            field=models.FileField(blank=True, null=True, upload_to='properties/documents/'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenancy_agreement',
            field=models.FileField(blank=True, null=True, upload_to='properties/documents/'),
        ),
    ]
