# Generated by Django 6.0.4 on 2026-05-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_property_building_plans_property_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
