# Generated by Django 6.0.4 on 2026-05-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agentrole_inspectionagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionagent',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='agents/'),
        ),
    ]
