# Generated by Django 6.0.4 on 2026-05-19 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_inspectionagent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('under_maintenance', 'Under Maintenance'), ('pending_verification', 'Pending Verification'), ('under_inspection', 'Under Inspection')], default='pending_verification', max_length=20),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Inspection'), ('in_progress', 'Inspection in Progress'), ('completed', 'Inspection Completed')], default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField()),
                ('status', models.CharField(choices=[('approved', 'Approved / Safe'), ('flagged', 'Flagged / Minor Concerns'), ('rejected', 'Rejected / Unsafe')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.inspectionagent')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.inspection')),
            ],
        ),
    ]
