# Generated by Django 6.0.4 on 2026-05-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_property_status_inspection_inspectionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionagent',
            name='agent_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
