# Generated by Django 6.0.4 on 2026-05-19 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_inspectionagent_agent_id_property_property_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('layer', models.CharField(choices=[('core', 'Core Details'), ('verification', 'Verification Details'), ('luxury', 'Luxury/Optional Amenities'), ('indoor', 'Indoor Amenities'), ('utilities', 'Utilities & Infrastructure'), ('security', 'Security Features'), ('outdoor', 'Outdoor Amenities'), ('building', 'Building Features'), ('location', 'Location & Convenience'), ('rental', 'Rental & Management Features'), ('commercial', 'Land & Commercial Property Features')], default='luxury', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProximityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProximityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.proximitycategory')),
            ],
        ),
    ]
