# Generated by Django 6.0.4 on 2026-05-19 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_propertyamenity_proximitycategory_proximityitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='core.propertyamenity'),
        ),
        migrations.CreateModel(
            name='PropertyProximity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proximityitem')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximities', to='core.property')),
            ],
            options={
                'unique_together': {('property', 'item')},
            },
        ),
    ]
