# Generated by Django 6.0.4 on 2026-05-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_property_amenities_propertyproximity'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
