# Generated by Django 6.0.4 on 2026-05-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_doctor_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbooking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantbooking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active'), ('expired', 'Expired'), ('paid_rent', 'Paid Rent & Finalized')], default='reserved', max_length=20),
        ),
    ]
