# Generated by Django 6.0.4 on 2026-05-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_favoriteproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('image', models.FileField(blank=True, null=True, upload_to='committee/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
