# Generated by Django 6.0.4 on 2026-05-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_servicedistrict_servicedivision_servicevillage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('popup_type', models.CharField(choices=[('marketing', 'Marketing & Promotion'), ('logistics', 'Logistics / Booking Flow')], default='marketing', max_length=20)),
                ('display_page', models.CharField(choices=[('search', 'Find a Property (Search Page)'), ('tenant_dashboard', 'Tenant Dashboard'), ('all', 'All Pages')], default='search', max_length=50)),
                ('trigger_event', models.CharField(choices=[('load', 'On Page Load'), ('payment_success', 'After Payment Completed (Redirect Trigger)')], default='load', max_length=50)),
                ('content', models.TextField(help_text='HTML/Text description of the offer or logistical guidelines')),
                ('image', models.FileField(blank=True, help_text='Popup hero graphic or icon', null=True, upload_to='popups/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
