# Generated by Django 6.0.4 on 2026-06-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_popuplogic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TRUST', max_length=100)),
                ('site_icon', models.FileField(blank=True, help_text='Favicon / Tab icon', null=True, upload_to='site_settings/')),
                ('site_logo', models.FileField(blank=True, help_text="Top header logo replacement for 'Shield and TRUST'", null=True, upload_to='site_settings/')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
