# Generated by Django 6.0.4 on 2026-08-07 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_chatthread_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPanorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Living Room, Master Bedroom, Balcony View', max_length=150)),
                ('panorama_type', models.CharField(choices=[('360', '360° Full Room Panorama'), ('180', '180° Balcony / Partial View')], default='360', max_length=10)),
                ('image', models.FileField(upload_to='properties/panoramas/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='core.property')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
