# Generated by Django 6.0.4 on 2026-08-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_propertypanorama'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate (e.g. 0.3476)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate (e.g. 32.5825)', null=True),
        ),
    ]
