# Generated by Django 6.0.4 on 2026-08-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_herovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='stat_agents',
            field=models.IntegerField(default=32, help_text='Agents Counter Display'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_districts',
            field=models.IntegerField(default=14, help_text='Districts Counter Display'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_landlords',
            field=models.IntegerField(default=85, help_text='Landlords Counter Display'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_properties',
            field=models.IntegerField(default=120, help_text='Properties Counter Display'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_tenants',
            field=models.IntegerField(default=450, help_text='Tenants Counter Display'),
        ),
    ]
