# Generated by Django 6.0.4 on 2026-08-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_sitesetting_stat_agents_sitesetting_stat_districts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='stat_moved_in',
            field=models.IntegerField(default=380, help_text='Moved In Counter Display'),
        ),
    ]
