# Generated by Django 6.0.4 on 2026-08-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_sitesetting_stat_moved_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='top_selling_image',
            field=models.FileField(blank=True, help_text='Top Selling Apartment Image uploaded by Admin', null=True, upload_to='featured/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='top_selling_link',
            field=models.CharField(default='/search/', help_text='Top Selling Apartment Link URL', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='top_selling_location',
            field=models.CharField(default='Kololo, Kampala', help_text='Top Selling Apartment Location', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='top_selling_price',
            field=models.CharField(default='UGX 2,500,000 / mo', help_text='Top Selling Apartment Price', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='top_selling_title',
            field=models.CharField(default='Penthouse Apartment in Kololo', help_text='Top Selling Apartment Title', max_length=200),
        ),
    ]
