# Generated by Django 6.0.4 on 2026-08-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_sitesetting_top_selling_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='pipeline_left_image',
            field=models.FileField(blank=True, help_text='Left Section Image uploaded by Admin', null=True, upload_to='pipeline/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='pipeline_right_image',
            field=models.FileField(blank=True, help_text='Right Section Image uploaded by Admin', null=True, upload_to='pipeline/'),
        ),
    ]
