# Generated by Django 6.0.4 on 2026-08-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_sitesetting_pipeline_left_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantrental',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenantrental',
            name='payment_type',
            field=models.CharField(choices=[('rent_2', '2 Months Rent'), ('rent_3', '3 Months Rent')], default='rent_2', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantrental',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
