# Generated by Django 6.0.4 on 2026-08-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tenantrental_created_at_tenantrental_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Heights Executive Villa - Naalya Phase 2', max_length=255)),
                ('location', models.CharField(blank=True, help_text='e.g. Naalya, Kampala, Uganda', max_length=255)),
                ('short_description', models.TextField(help_text='Brief summary of the ongoing construction work')),
                ('full_description', models.TextField(blank=True, help_text='Detailed project specifications, materials, and milestones')),
                ('video', models.FileField(blank=True, help_text='Upload MP4 video demonstrating construction progress', null=True, upload_to='project_videos/')),
                ('video_url', models.URLField(blank=True, help_text='Optional external video URL (e.g. MP4 or YouTube embed link)')),
                ('thumbnail', models.ImageField(blank=True, help_text='Project cover image poster', null=True, upload_to='project_thumbnails/')),
                ('progress_percentage', models.IntegerField(default=0, help_text='Construction completion percentage (0 to 100)')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing Construction'), ('completed', 'Completed Project'), ('upcoming', 'Upcoming Project')], default='ongoing', max_length=20)),
                ('supervisor_name', models.CharField(blank=True, default='TRUST Engineering & Supervision Unit', max_length=150)),
                ('client_name', models.CharField(blank=True, help_text='Optional client/owner reference', max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
