# Generated by Django 6.0.4 on 2026-08-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_constructionproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasporaClientApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_or_id', models.CharField(help_text='Passport Number or National ID Number', max_length=100)),
                ('id_document', models.FileField(blank=True, help_text='Passport or ID Upload', null=True, upload_to='diaspora_ids/')),
                ('country_of_residence', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('land_proof', models.FileField(blank=True, help_text='Proof of land ownership: Title, Agreement, or Search Letter', null=True, upload_to='diaspora_land_proofs/')),
                ('district', models.CharField(max_length=150)),
                ('sub_county', models.CharField(blank=True, max_length=150)),
                ('village', models.CharField(blank=True, max_length=150)),
                ('building_plans', models.FileField(blank=True, help_text='Building plans or architectural concept files', null=True, upload_to='diaspora_plans/')),
                ('building_concept_notes', models.TextField(blank=True, help_text='Building concept notes or custom specs')),
                ('budget_range', models.CharField(help_text='e.g. UGX 100M - 250M', max_length=100)),
                ('preferred_timeline', models.CharField(help_text='e.g. Immediate (1-3 months)', max_length=100)),
                ('next_of_kin_name', models.CharField(max_length=255)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=100)),
                ('next_of_kin_phone', models.CharField(max_length=50)),
                ('next_of_kin_district', models.CharField(blank=True, max_length=150)),
                ('payment_method', models.CharField(choices=[('swift', 'SWIFT Wire Transfer'), ('bank_direct', 'Direct Bank Transfer'), ('escrow', 'TRUST Escrow Account'), ('mobile_money', 'Mobile Money (MTN / Airtel)'), ('other', 'Other Arrangement')], default='swift', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Verification'), ('approved', 'Approved & Contract Active'), ('rejected', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
