# Generated by Django 6.0.4 on 2026-08-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_diasporaclientapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='diasporaclientapplication',
            name='construction_budget_range',
            field=models.CharField(blank=True, help_text='Construction budget range', max_length=100),
        ),
        migrations.AddField(
            model_name='diasporaclientapplication',
            name='desired_land_size',
            field=models.CharField(blank=True, help_text='e.g. 50x100 ft, 100x100 ft, 1 Acre', max_length=100),
        ),
        migrations.AddField(
            model_name='diasporaclientapplication',
            name='desired_land_type',
            field=models.CharField(blank=True, help_text='Agricultural, Rental setup, Commercial, Urban, Off-town residential', max_length=100),
        ),
        migrations.AddField(
            model_name='diasporaclientapplication',
            name='land_budget_range',
            field=models.CharField(blank=True, help_text='e.g. UGX 30M - 70M', max_length=100),
        ),
        migrations.AddField(
            model_name='diasporaclientapplication',
            name='owns_land',
            field=models.CharField(default='yes', help_text='yes or no', max_length=10),
        ),
        migrations.AlterField(
            model_name='diasporaclientapplication',
            name='budget_range',
            field=models.CharField(blank=True, help_text='e.g. UGX 100M - 250M', max_length=100),
        ),
    ]
