# Generated by Django 6.0.4 on 2026-08-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_diasporaclientapplication_construction_budget_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diasporaclientapplication',
            name='applicant_photo',
            field=models.ImageField(blank=True, help_text='Applicant Passport Size Photo', null=True, upload_to='diaspora_photos/'),
        ),
    ]
