# Generated by Django 6.0.4 on 2026-08-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_diasporaclientapplication_applicant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionproject',
            name='completed_milestones',
            field=models.JSONField(blank=True, default=list, help_text='List of completed milestone numbers (1 to 25)'),
        ),
    ]
