# Generated by Django 6.0.4 on 2026-08-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_constructionproject_completed_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='rent', max_length=20),
        ),
    ]
