# Generated by Django 6.0.4 on 2026-08-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_property_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_4',
            field=models.FileField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_5',
            field=models.FileField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_6',
            field=models.FileField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_7',
            field=models.FileField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
    ]
