# Generated by Django 6.0.4 on 2026-08-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_property_image_4_property_image_5_property_image_6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionproject',
            name='hero_image',
            field=models.FileField(blank=True, help_text='Project hero/cover image', null=True, upload_to='project_thumbnails/'),
        ),
    ]
