# Generated by Django 6.0.4 on 2026-08-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_userprofile_is_2fa_enabled_userprofile_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='electricity_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, help_text='e.g. 3rd Floor, Suite 3B', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='office_pricing_unit',
            field=models.CharField(blank=True, choices=[('per_table', 'Per Table'), ('per_sqm', 'Per Square Meter')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='water_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('single_room', 'Single Room'), ('self_contained', 'Self-Contained Room'), ('studio', 'Studio Apartment'), ('1_bed', '1 Bedroom Apartment'), ('2_bed', '2 Bedroom Apartment'), ('3_plus_bed', '3+ Bedroom Apartment'), ('bungalow', 'Bungalow'), ('standalone', 'Standalone House'), ('apartment_block', 'Apartment Block'), ('condo_block', 'Condominium Block'), ('flat', 'Flat (Multi-Floor Building)'), ('private_office', 'Private Office'), ('shared_office', 'Shared Office'), ('office_building', 'Office Building / Complex')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantbooking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('active', 'Paid'), ('reserved', 'Paid'), ('failed_payment', 'Failed payment'), ('expired', 'Failed payment'), ('paid_rent', 'Paid')], default='pending_payment', max_length=30),
        ),
    ]
