# Generated by Django 6.0.4 on 2026-08-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_property_electricity_cost_property_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group', models.CharField(choices=[('single_unit', 'Single Unit Residential'), ('multi_unit', 'Multi-Unit Residential (Building / Estate)'), ('multi_floor', 'Multi-Floor Building (Flat)'), ('office', 'Commercial / Office Space')], default='single_unit', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Property Categories',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('single_room', 'Single Room'), ('self_contained', 'Self-Contained Room'), ('studio', 'Studio Apartment'), ('1_bed', '1 Bedroom Apartment'), ('2_bed', '2 Bedroom Apartment'), ('3_plus_bed', '3+ Bedroom Apartment'), ('bungalow', 'Bungalow'), ('standalone', 'Standalone House'), ('apartment_block', 'Apartment Block'), ('condo_block', 'Condominium Block'), ('flat', 'Flat (Multi-Floor Building)'), ('private_office', 'Private Office'), ('shared_office', 'Shared Office'), ('office_building', 'Office Building / Complex')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='core.propertycategory'),
        ),
    ]
