# Generated by Django 6.0.4 on 2026-08-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_officeapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officeapplication',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='officeapplication',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='officeapplication',
            name='brn',
            field=models.CharField(default='BRN-PENDING', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officeapplication',
            name='cert_doc',
            field=models.FileField(blank=True, null=True, upload_to='office_certs/'),
        ),
        migrations.AddField(
            model_name='officeapplication',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='office_logos/'),
        ),
        migrations.AddField(
            model_name='officeapplication',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officeapplication',
            name='payment_status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='officeapplication',
            name='industry',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
