# Generated by Django 6.0.4 on 2026-08-27 16:20

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_founder_image',
            field=models.FileField(blank=True, help_text='About Us Founder Story Image uploaded by Admin', null=True, upload_to='site_settings/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_hero_image',
            field=models.FileField(blank=True, help_text='About Us Premium Hero Image uploaded by Admin', null=True, upload_to='site_settings/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='hero_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='properties/hero/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_5',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_6',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_7',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='properties/gallery/'),
        ),
    ]
