# Generated by Django 6.0.4 on 2026-08-29 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_sitesetting_about_founder_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='collect_rent_by_trust',
            field=models.BooleanField(default=True, help_text='Do you want TRUST PROTOCOL to collect Rent from your Tenants'),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='core.servicedistrict'),
        ),
        migrations.AddField(
            model_name='property',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='core.servicedivision'),
        ),
        migrations.AddField(
            model_name='property',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='core.servicevillage'),
        ),
        migrations.CreateModel(
            name='RentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text='e.g. Single Room #01 or Unit 3B', max_length=100)),
                ('property_category', models.CharField(blank=True, help_text='Category name from PropertyCategory', max_length=100, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('grace_period', 'Grace Period'), ('vacant', 'Vacant')], default='vacant', max_length=30)),
                ('trust_collects_rent', models.BooleanField(default=True, help_text='Whether TRUST Protocol handles rent collection for this unit')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_rent_collections', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_collections', to='core.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_rent_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rent Collection',
                'verbose_name_plural': 'Rent Collections',
                'ordering': ['property_category', 'unit_number'],
            },
        ),
    ]
