# Generated by Django 6.0.4 on 2026-08-31 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_property_collect_rent_by_trust_property_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionagent',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='core.servicedistrict'),
        ),
        migrations.AddField(
            model_name='inspectionagent',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='core.servicedivision'),
        ),
    ]
