# Generated by Django 6.0.4 on 2026-08-31 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_inspectionagent_district_inspectionagent_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingrequest',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_viewings', to='core.inspectionagent'),
        ),
    ]
