# Generated by Django 6.0.4 on 2026-09-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_viewingrequest_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_contact_image',
            field=models.FileField(blank=True, help_text='About Us Contact Form Left Image uploaded by Admin', null=True, upload_to='site_settings/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_mission_image_1',
            field=models.FileField(blank=True, help_text='About Us Mission Image 1 uploaded by Admin', null=True, upload_to='site_settings/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_mission_image_2',
            field=models.FileField(blank=True, help_text='About Us Mission Image 2 uploaded by Admin', null=True, upload_to='site_settings/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_pillars_image_1',
            field=models.FileField(blank=True, help_text='About Us Pillars Image 1 uploaded by Admin', null=True, upload_to='site_settings/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_pillars_image_2',
            field=models.FileField(blank=True, help_text='About Us Pillars Image 2 uploaded by Admin', null=True, upload_to='site_settings/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_work_video_image',
            field=models.FileField(blank=True, help_text='About Us How We Work Video Showcase Image uploaded by Admin', null=True, upload_to='site_settings/'),
        ),
    ]
